name: 'Continuous Integration [CI]'

on:
  pull_request:
    types: [synchronize, opened]

env:
  MARVEL_PUBLIC_KEY: ${{secrets.NEXT_PUBLIC_MARVEL_SECRET_KEY}}
  MARVEL_SECRET_KEY: ${{secrets.NEXT_PUBLIC_MARVEL_SECRET_KEY}}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: ls -la
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint fix
        run: yarn lint:fix
